SELECT CROP_STRESS_TYPE,location_id, COUNT(CROP_STRESS_TYPE) as Total FROM public.observations
WHERE CROP_STRESS_TYPE IS NOT NULL
GROUP BY CROP_STRESS_TYPE,LOCATION_ID 
ORDER BY CROP_STRESS_TYPE,LOCATION_ID  ASC LIMIT 100
