/**
 * Methodology data — derived from data/reports/comparison.json, generated by
 * scripts/compare_models.py on 2026-05-04. Test split is observations from
 * 2024-01-01 onwards (held out during training). n=30 per model, all 10
 * fields evaluated.
 *
 * Keep in sync if the comparison data changes. The shape mirrors the eval
 * report at data/reports/AquaVeritas_Eval_Report_2026-05-04.md.
 */

export type FieldKey =
  | "water_extent_status"
  | "flood_risk"
  | "water_clarity"
  | "shoreline_encroachment"
  | "agriculture_present"
  | "crop_stress_level"
  | "crop_stress_type"
  | "cultivation_expanding_toward_water"
  | "settlement_visible"
  | "bare_soil_expansion";

export type Zone = "core" | "buffer";

export interface FieldRow {
  field: FieldKey;
  label: string;
  zone: Zone;
  /** Valid values for this field (categorical) — shown as captions. */
  valid: string;
  claude: number;
  base: number;
  finetuned: number;
}

export const FIELDS: FieldRow[] = [
  // ── Core zone ──────────────────────────────────────────────────────────────
  {
    field: "water_extent_status",
    label: "Water extent",
    zone: "core",
    valid: "shrinking · stable · flooded · recovering · dry",
    claude: 0.900,
    base: 0.033,
    finetuned: 0.867,
  },
  {
    field: "flood_risk",
    label: "Flood risk",
    zone: "core",
    valid: "none · elevated · active",
    claude: 0.767,
    base: 0.300,
    finetuned: 0.800,
  },
  {
    field: "water_clarity",
    label: "Water clarity",
    zone: "core",
    valid: "clear · turbid · heavily silted",
    claude: 0.933,
    base: 0.133,
    finetuned: 0.967,
  },
  {
    field: "shoreline_encroachment",
    label: "Shoreline encroachment",
    zone: "core",
    valid: "yes / no",
    claude: 0.833,
    base: 0.133,
    finetuned: 0.967,
  },
  // ── Buffer zone ────────────────────────────────────────────────────────────
  {
    field: "agriculture_present",
    label: "Agriculture present",
    zone: "buffer",
    valid: "yes / no",
    claude: 0.867,
    base: 0.300,
    finetuned: 0.667,
  },
  {
    field: "crop_stress_level",
    label: "Crop stress level",
    zone: "buffer",
    valid: "none · low · moderate · severe",
    claude: 0.767,
    base: 0.133,
    finetuned: 0.567,
  },
  {
    field: "crop_stress_type",
    label: "Crop stress type",
    zone: "buffer",
    valid: "drought · flood damage · none",
    claude: 0.700,
    base: 0.000,
    finetuned: 0.833,
  },
  {
    field: "cultivation_expanding_toward_water",
    label: "Cultivation → water",
    zone: "buffer",
    valid: "yes / no",
    claude: 0.933,
    base: 0.167,
    finetuned: 0.967,
  },
  {
    field: "settlement_visible",
    label: "Settlement visible",
    zone: "buffer",
    valid: "yes / no",
    claude: 0.967,
    base: 0.300,
    finetuned: 0.933,
  },
  {
    field: "bare_soil_expansion",
    label: "Bare soil expansion",
    zone: "buffer",
    valid: "yes / no",
    claude: 0.967,
    base: 0.300,
    finetuned: 0.967,
  },
];

export interface ModelHeadline {
  id: "claude" | "base" | "finetuned";
  label: string;
  params: string;
  overall: number;
  core: number;
  buffer: number;
}

export const HEADLINES: ModelHeadline[] = [
  {
    id: "claude",
    label: "Claude Opus oracle",
    params: "~200B",
    overall: 0.863,
    core: 0.858,
    buffer: 0.867,
  },
  {
    id: "base",
    label: "LFM2.5-VL-450M base",
    params: "450M",
    overall: 0.180,
    core: 0.150,
    buffer: 0.200,
  },
  {
    id: "finetuned",
    label: "AquaVeritas fine-tuned",
    params: "450M",
    overall: 0.854,
    core: 0.900,
    buffer: 0.822,
  },
];

/** Number to a percentage string, no decimals. */
export const pct = (x: number): string => `${(x * 100).toFixed(0)}%`;
/** As percentage points (for deltas), one decimal. */
export const pp = (x: number): string => `${(x * 100).toFixed(1)}`;
